variable "region" {}
variable "vpc_id" {}
variable "ami" {}
variable "instance_type" {}
variable "public_subnet_id" {}
variable "key_name" {}
variable "bastion_sg_name" {}
variable "private_instance_sg_name" {}
variable "private_instance_role_name" {}
variable "assume_role_policy" {}
variable "policy_arn" {}
variable "bastion_instance_name" {}
variable "private_instance_name" {}
variable "private_subnet_id" {}
variable "public_subnet_cidr" {}
variable "private_key_path" {}