variable "region" {}
variable "cidr_block" {}
variable "vpc_name" {}
variable "public_subnet_cidr" {}
variable "availability_zone" {}
variable "public_subnet_name" {}
variable "private_subnet_cidr" {}
variable "private_subnet_name" {}
variable "igw_name" {}
variable "public_route_table_name" {}
