name: Terraform Plan and Apply

on:
  workflow_dispatch:
    inputs:
      uninstall:
        description: 'Destroy'
        required: true
        default: 'no'
  push:
    branches:
      - main

jobs:
  uninstall:
    runs-on: ubuntu-latest
    if: github.event.inputs.uninstall == 'yes'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: destroy resources
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

  terraform:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.inputs.uninstall == 'no'   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Clean up Terraform files
        run: rm -rf .terraform tfplan
